Sextant.Tests/Mocks/PageMock.cs, Sextant.Tests/Mocks/PageViewModelMock.cs, Sextant.Tests/Navigation/ViewStackServiceFixture.cs, Sextant.Tests/Navigation/ViewStackServiceFixtureExtensions.cs, Sextant.Tests/Navigation/ViewStackServiceTests.cs, Sextant.Tests/Sextant.Tests.csproj, Sextant.sln, Sextant/Navigation/Abstraction/IViewStackService.cs, Sextant/Navigation/NavigationView.cs, Sextant/Navigation/ViewStackService.cs
This PR is for #15 
I added the following: 
- View Stack Service unit test
- TopModal and TopPage to display what is currently on the top of the stack
=> (GH-15) Added ViewServiceStack Unit Tests

Sextant.Tests/Mocks/PageViewModelMock.cs, Sextant.Tests/Navigation/ViewStackServiceFixture.cs, Sextant.Tests/Navigation/ViewStackServiceFixtureExtensions.cs, Sextant.Tests/Navigation/ViewStackServiceTests.cs, Sextant/Navigation/NavigationView.cs, Sextant/Navigation/ViewStackService.cs
@giusepe This doesn't solve your problem, I believe the unit tests now cover the scenario you were concerned about.  I cleaned up some of the tests.  Hopefully made them more readable.
=> Added Test to check for Push and Pop

README.md, Sextant.Tests/Navigation/ViewStackServiceTests.cs, appveyor.yml, build.cake, build.ps1, cake.config
- Fixed link in README.md
This PR adds Unit test execution to the build pipeline.  I commented out the failing test.  I have a separate branch trying to fix those.
=> (GH-22) Added Run-Unit-Test to Cake build

Sample/SextantSample.Android/SextantSample.Android.csproj, Sample/SextantSample.iOS/SextantSample.iOS.csproj, Sample/SextantSample/SextantSample.csproj, Sample/SextantSample/Views/FirstModalView.xaml, Sample/SextantSample/Views/HomeView.xaml, Sample/SextantSample/Views/RedView.xaml, Sample/SextantSample/Views/SecondModalView.xaml, Sextant.Tests/Sextant.Tests.csproj, Sextant/Sextant.csproj
=> Updated package dependencies for System.Reactive 4.0.0 (#31)

README.md
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
README update.
**What is the current behavior? (You can also link to an open issue here)**
Extra whitespace is present.
**What is the new behavior (if this is a feature change)?**
Extra whitespace is removed!
Nothing.
=> Remove whitespace from README.md

src/Directory.build.props
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adds a nuget package description.
**What is the current behavior? (You can also link to an open issue here)**
There is no description.
**What is the new behavior (if this is a feature change)?**
There is a description
Nothing.
=> housekeeping: Added nuget package description

.github/opencollective.yml, .github/release-drafter.yml
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Added .github folder with bot configuration
**What is the current behavior? (You can also link to an open issue here)**
No config.
**What is the new behavior (if this is a feature change)?**
Open Collective bot config
Release Generator config
bots
=> housekeeping: Added .github folder

src/Benchmarks/Mocks/BenchmarkView.cs, src/Benchmarks/Mocks/InMemoryViewLocator.cs, src/Benchmarks/Mocks/TestView.cs, src/Benchmarks/Mocks/ViewModel.cs, src/Benchmarks/Program.cs, src/Benchmarks/Sextant.Benchmarks.csproj, src/Benchmarks/Sextant.Benchmarks.sln, src/Benchmarks/ViewStackServiceBenchmark.cs
Adds a Benchmark DotNet solution
Resolves: #60 
There is a Harness for performance information.
Nothing.
=> performance: Add Benchmarks

README.md, src/Sextant.XamForms/Mixins/DependencyResolverMixins.cs, src/Sextant.XamForms/Sextant.XamForms.csproj, src/Sextant/DependencyResolverMixins.cs, src/Sextant/Navigation/ParameterViewStackService.cs, src/Sextant/Navigation/ViewStackServiceBase.cs
Adds documentation for Sextant 2.0 features.
Resolves: #107, #79 
=> housekeeping: Added Sextant 2.0 Documentation

Sample/SextantSample.Android/SextantSample.Android.csproj, Sample/SextantSample.iOS/SextantSample.iOS.csproj, Sample/SextantSample/SextantSample.csproj, src/Directory.build.props, src/Directory.build.targets, src/Sextant.Tests/API/ApiApprovalTests.SextantProject.net472.approved.txt, src/Sextant.Tests/API/ApiApprovalTests.SextantProject.netcoreapp2.2.approved.txt, src/Sextant.XamForms/Sextant.XamForms.csproj, src/Sextant/DependencyResolverMixins.cs, src/Sextant/Sextant.csproj
Solves #133, #132, #118, #114 
Upgrades dependencies.
Nothing.
=> housekeeping: Updated to ReactiveUI 10

src/Sextant.XamForms/Sextant.XamForms.csproj, src/global.json
Fixes the build and updates Xamarin.Forms to version 4.2.*
Currently It targets Xamarin.Forms 4.0.*
Will target Xamarin.Forms 4.2.*
Sextant.XamForms
=> housekeeping: Upgraded Xamarin.Forms to v4.2

Sample/SextantSample.Android/SextantSample.Android.csproj, src/Sextant.Mocks/Sextant.Mocks.csproj, src/Sextant.XamForms/Sextant.XamForms.csproj, src/global.json
Fixes building the samples on macOS
Currently there is an issue building the samples of macOS
The sample builds on macOS
Building the sample
=> fix: Build sample on macOS

src/Sextant.Mocks/Mocks/ParameterViewModel.cs, src/Sextant.Tests/Mocks/NavigatedMock.cs, src/Sextant.Tests/Navigation/NavigatedTests.cs, src/Sextant.Tests/Navigation/NavigatingTests.cs, src/Sextant.Tests/Navigation/ParameterViewStackServiceFixture.cs, src/Sextant.XamForms.Tests/SextantExtensionTests.cs, src/Sextant.iOS.Runner/PageUiViewController.cs, src/Sextant.iOS.Runner/Properties/AssemblyInfo.cs, src/Sextant.iOS.Runner/TestViewLocator.cs
Cleaned up compile time errors and warnings
The compiler yells
The compiler is quiet
Nothing.
=> housekeeping: Clean up analyzer errors and warnings

README.md
Adds a link to the  platform minimum versions
There is not link to the minimum versions
There is a link to the minimum version
Nothing
=> housekeeping: Added link to ReactiveUI minimum versions

Sample/SextantSample/SextantSample.csproj, src/Sextant.XamForms/Sextant.XamForms.csproj
Upgrades Xamarin.Forms to v4.3
Xamarin.Forms references to v4.2
Xamarin.Forms references to v4.3
Sextant.XamForms
=> housekeeping: Upgraded Xamarin.Forms to v4.3

Sample/SextantSample.Android/SextantSample.Android.csproj, Sample/SextantSample.iOS/SextantSample.iOS.csproj, Sample/SextantSample/SextantSample.csproj, src/Directory.build.props, src/Sextant.XamForms/Sextant.XamForms.csproj, src/Sextant/Sextant.csproj
Upgraded ReactiveUI to v11
Targets ReactiveUI is on v10
Target ReactiveUI v11
Everything
=> housekeeping: Upgraded to ReactiveUI v11

Sample/SextantSample/SextantSample.csproj
Migrating Pharmacist to 1.*
Targeting Pharmacist v1.2.*
Targeting Pharmacist 1.*
The sample.
=>  housekeeping: Migrated Pharmacist to 1.*

README.md
Adds UWP to the NuGet Package Matrix
UWP is not listed
UWP is listed
Nothing
=> housekeeping: Added UWP to NuGet matrix

src/Sextant.XamForms/Sextant.XamForms.csproj
Updates Xamarin.Forms to version 4.4.*
We depend on Xamarin 4.3.*
Depending on Xamarin 4.4.*
Sextant.XamForms
This follows our policy for [Xamarin.Forms minimum version](https://reactiveui.net/contribute/maintainers/platform-knowledge/xamarin-forms/#when-to-bump)
=> housekeeping: Upgraded Xamarin.Forms to v4.4

version.json
=> release: Sextant v2.6

version.json
=> release: Sextant v2.7

build.config
Updates Cake to v0.38.1
The most updated version of ReactiveUI.Cake.Recipe is broken
The ReactiveUI.Cake.Recipe works
Nothing
=> housekeeping: Update Cake to v0.38.1

build.config
=> Housekeeping: update cake version

src/Sextant/Platforms/uikit-common/NavigationViewController.cs
Removes an extra assignment of a value that is already available.
allocates a value to pass 
value is taken from the observable pipeline
Sextant.iOS
=> fix: remove unnecessary allocation

Sample/SextantSample.sln
Fix project reference within Sample solution to include ViewModel project
Errors because no reference to ViewModel project
Add reference to ViewModel project within Sample Solution
Nothing
=> fix: Sample project

version.json
release version 2.8
version 2.7
version 2.8
=> release: Sextant v2.8

src/Sextant.XamForms/SextantHelper.cs
resolves: #306 
The Obsolete method wasn't updated with new functionality.
The obsolete method now registers the proper dependencies.
Nothing that isn't broken.
=> fix: Initialize not registering ViewModelFactory

version.json
=> housekeeping: Release Sextant v2.12

src/Sextant.XamForms.Tests/Sextant.XamForms.Tests.csproj, src/Sextant.XamForms/Sextant.XamForms.csproj
=> housekeeping: Upgraded Xamarin.Forms to v5

README.md
=> housekeeping: Adding Sextan.Plugins.Popup to README

Sample/SextantSample.Android/SextantSample.Android.csproj, Sample/SextantSample.Avalonia/SextantSample.Avalonia.csproj, Sample/SextantSample.Core/SextantSample.ViewModels.csproj, Sample/SextantSample/SextantSample.csproj, src/Directory.build.props, src/Sextant.Plugins.Popup.Tests/Sextant.Plugins.Popup.Tests.csproj, src/Sextant.Tests/Sextant.Tests.csproj, src/Sextant.XamForms.Tests/Sextant.XamForms.Tests.csproj, src/Sextant.XamForms/Sextant.XamForms.csproj, src/Sextant/DependencyResolverMixins.cs
fix
**What is the current behaviour?**
Dependabot is too noisy which leads to broken builds
**What is the new behaviour?**
Removed duplicated dependencies to minimise Dependabot activity
none
**Please check if the PR fulfils these requirements**
=> fix Tidied up projects to minimise on dependencies

.github/workflows/build-samples.yml, .github/workflows/ci-build.yml, .github/workflows/release.yml, src/Directory.Packages.props
Update
Using ReactiveUI 20.1.63
=> Housekeeping Update ReactiveUI Version

src/global.json
=> Housekeeping Delete global.json
