Sample/SextantSample/ViewModels/RedViewModel.cs
Sample/SextantSample/Views/RedView.xaml
Sample/SextantSample/Views/RedView.xaml.cs
src/Directory.build.props
src/Sextant.Tests/Mocks/PageViewModelMock.cs
src/Sextant.Tests/Navigation/ViewStackServiceFixture.cs
src/Sextant.Tests/Navigation/ViewStackServiceFixtureExtensions.cs
src/Sextant.Tests/Navigation/ViewStackServiceTests.cs
src/Sextant/Navigation/ViewStackService.cs
src/Sextant/Sextant.csproj

Added some test coverage and fixed a few issues
- ViewStackService properties now properly return observables
- PopToRoot will now notify that it has popped an item from the stack
- PopToRoot will now clear the stack after it has completed
Resolves: #57 
`PopToRoot` clears the `ViewStackService.PageStack`
Nothing

fix: PopToRoot doesn't clear PageStack

---

Sample/SextantSample/Interactions.cs
Sample/SextantSample/ViewModels/FirstModalViewModel.cs
Sample/SextantSample/ViewModels/HomeViewModel.cs
Sample/SextantSample/ViewModels/RedViewModel.cs
Sample/SextantSample/ViewModels/SecondModalViewModel.cs
Sample/SextantSample/Views/FirstModalView.xaml.cs
Sample/SextantSample/Views/HomeView.xaml.cs
Sample/SextantSample/Views/RedView.xaml.cs
Sample/SextantSample/Views/SecondModalView.xaml.cs

Adds interactions to display error messages.  Just a nicety to show off **a** use for Interactions from the ReactiveUI framework.
The sample will crash if you hit an unexpected error.
The sample will display the `Message` portion of an Exception thrown from a ReactiveCommand
Samples

housekeeping: Added Error Interactions to Sextant Sample

---

src/Sextant.Tests/API/ApiApprovalTests.SextantProject.net472.approved.txt
src/Sextant.Tests/API/ApiApprovalTests.SextantProject.netcoreapp2.2.approved.txt
src/Sextant/Abstractions/IParameterViewStackService.cs

Extend IParameterViewStackService from IViewStackService
It doesn't extend and you cannot use `IViewStackService` methods from the interface.
You can access `IViewStackService` methods from `IParameterViewStackService`
Nothing

fix: IParameterViewStackService extends IViewStackService

---

src/Sextant.Tests/API/ApiApprovalTests.SextantProject.net472.approved.txt
src/Sextant.Tests/API/ApiApprovalTests.SextantProject.netcoreapp2.2.approved.txt
src/Sextant.Tests/Navigation/ParameterViewStackServiceTests.cs
src/Sextant.XamForms.Tests/API/ApiApprovalTests.SextantProject.net472.approved.txt
src/Sextant.XamForms.Tests/API/ApiApprovalTests.SextantProject.netcoreapp2.2.approved.txt
src/Sextant.XamForms/NavigationView.cs
src/Sextant/Abstractions/IView.cs
src/Sextant/Navigation/ParameterViewStackService.cs
src/Sextant/Platforms/uikit-common/NavigationViewController.cs

While creating a sample for navigation parameters, I found that ReactiveUI bindings are failing to update.
Bindings are failing.
I made sure the `INavigable` functions happen on the UI thread.
Navigation Parameters

fix: Passing parameters breaking ReactiveUI bindings

---

README.md
logo/horizontal.png
logo/logo.png
logo/vertical.png
src/Directory.build.props

Sourcing images for Sextant from the styleguide repository.
Logos exist in the Sextant repository.
Sextant logos exist in the styleguide repository.
Images on NuGet packages.

housekeeping: Source logo from styleguide repository

---

src/global.json

Adds dotnet sdk version to the global.json as outlined in the [MsBuild.Sdk.Extras documentation](https://github.com/onovotny/MSBuildSdkExtras#getting-started-vs-156).
The build is broken
The build is working.
Nothing the build is already broke.

housekeeping: Added dotnet sdk version to global.json

---

src/Sextant.XamForms.Tests/API/ApiApprovalTests.SextantProject.net472.approved.txt
src/Sextant.XamForms.Tests/API/ApiApprovalTests.SextantProject.netcoreapp2.2.approved.txt
src/Sextant.XamForms/NavigationView.cs

Adds a default `NavigationView()` constructor for the Xamarin Forms implementation.
You currently have to provide `RxApp.MainThreadScheduler`, `RxApp.TaskpoolScheduler` and `ViewLocator.Current` any time you want to create an `NavigationView` instance.  The defaults are most likely what you will pass so we should provide a way to pass them.
You can instantiate a `NavigationView` with a default constructor and no arguments `NavigationView()`
Itself.

feature: Added default NavigationView constructor

---

Sample/SextantSample.Android/Properties/AndroidManifest.xml
Sample/SextantSample.Android/Resources/Resource.designer.cs
Sample/SextantSample.Android/SextantSample.Android.csproj
Sample/SextantSample/SextantSample.csproj

- Changed Droid sample target framework to 9 as it was making the wrong main thread scheduler to be resolved by scheduling with `RxApp.MainThreadScheduler`
- Consolidated using Xamarin 4.2.* on the sample (as the other projects do)
Bug fix
#171
The `RxApp.MainThreadScheduler` resolves correctly to the main thread.

fix: Changed Droid sample target framework to 9

---

Sample/SextantSample/Views/FirstModalView.xaml
Sample/SextantSample/Views/GreenView.xaml
Sample/SextantSample/Views/HomeView.xaml
Sample/SextantSample/Views/RedView.xaml
Sample/SextantSample/Views/SecondModalView.xaml

The Xamarin.Forms Sample is broken.  It won't build due to namespacing issues.
The Xamarin.Forms Sample works
The namespaces are correctly resolved for the Xamarin.Forms sample and it builds.
Nothing.

fix: SextantSample ViewModel namespacing

---

src/Sextant.Mocks/Mocks/NavigableViewModelMock.cs
src/Sextant.Mocks/Mocks/NavigationViewMock.cs
src/Sextant.Mocks/Mocks/PageView.cs
src/Sextant.Mocks/Mocks/ParameterViewModel.cs
src/Sextant.Mocks/Sextant.Mocks.csproj
src/Sextant.Tests/Navigation/ParameterViewStackServiceTests.cs
src/Sextant.XamForms/NavigationView.cs
src/Sextant/Navigation/ParameterViewStackService.cs
src/Sextant/Navigation/ViewStackServiceBase.cs

Fixes the `PopPage(INavigationParameter parameter)` not firing the `INavigable` `WhenNavigatedTo` function.
Resolves: #190 
Popping an `INavigable` implementation should call the associated `WhenNavigatedTo` method when navigating back to the view model.
`PopPage(INavigationParameter parameter)`

fix: Pop not firing WhenNavigatedTo

---

Sample/SextantSample.iOS/SextantSample.iOS.csproj

Moving ReactiveUI.XamForms back to the 11.* wildcard.
ReactiveUI.XamForms targets 11.1.1
ReactiveUI.XamForms targets 11.* wildcard.
Nothing

housekeeping: USample to ReactiveUI 11.*

---

Sample/SextantSample/SextantSample.csproj
src/Sextant.XamForms/Sextant.XamForms.csproj

Upgrades Xamarin.Forms minimum version to v4.5.*
Xamarin.Forms minimum version is 4.4.*
Xamarin.Forms minimum version is 4.5.*
Sextant.XamForms

housekeeping: Upgraded Xamarin.Forms to v4.5

---

src/Sextant.XamForms/NavigationView.cs
src/Sextant/System/Reactive/Linq/ToSignalExtension.cs
src/Sextant/System/Reactive/Linq/WhereNotNullExtension.cs

Deprecating custom extension methods.
When the library was written it had a `WhereNotNull()` and `ToSignal()` operators.  They have been marked obsolete because they cause namespace conflicts if another package has a similarly named operator in the `System.Reactive.Linq` namespace.
These operators are marked deprecated and will be removed in the next major version.
Nothing

housekeeping: Deprecated System.Reactive.Linq extension methods

---

src/Sextant.Tests/API/ApiApprovalTests.SextantProject.net472.approved.txt
src/Sextant.Tests/API/ApiApprovalTests.SextantProject.netcoreapp2.2.approved.txt
src/Sextant.Tests/Navigation/ParameterViewStackServiceTests.cs
src/Sextant/Abstractions/IParameterViewStackService.cs
src/Sextant/Navigation/ParameterViewStackService.cs

fixes issue where `INavigable.WhenNavigatingTo` doesn't fire before the target page navigation.
Nothing

fix: WhenNavigatingTo firing after page navigation

---

src/Sextant.Mocks/Mocks/IEverything.cs
src/Sextant.Mocks/Mocks/NavigationViewMock.cs
src/Sextant.Mocks/Mocks/ParameterViewModel.cs
src/Sextant.Tests/API/ApiApprovalTests.SextantProject.net472.approved.txt
src/Sextant.Tests/API/ApiApprovalTests.SextantProject.netcoreapp2.2.approved.txt
src/Sextant.Tests/Navigation/DestructibleTests.cs
src/Sextant.Tests/Navigation/ParameterViewStackServiceFixture.cs
src/Sextant.Tests/Navigation/ParameterViewStackServiceTests.cs
src/Sextant.Tests/Navigation/ViewStackServiceTests.cs
src/Sextant/Abstractions/IDestructible.cs
src/Sextant/Navigation/LifeCycleExtensions.cs
src/Sextant/Navigation/NavigationParameter.cs
src/Sextant/Navigation/ParameterViewStackService.cs
src/Sextant/Navigation/ViewModelActionExtensions.cs
src/Sextant/Navigation/ViewStackServiceBase.cs

Resolves: #197
There is no way to dispose of ViewModel subscriptions when a corresponding page is popped from the stack.
There is an `IDestructible` interface that allows you to dispose of view model resources when the page is popped from the view.
Lifecycle events.

[WIP] - feature: Add IDestructible lifecycle extension point 

---

src/Sextant.Tests/API/ApiApprovalTests.SextantProject.net472.approved.txt
src/Sextant.Tests/API/ApiApprovalTests.SextantProject.netcoreapp2.2.approved.txt
src/Sextant.Tests/API/ApiApprovalTests.cs
src/Sextant.Tests/DependencyResolverMixinTests.cs
src/Sextant.Tests/Navigation/DestructibleTests.cs
src/Sextant.Tests/Navigation/NavigatedTests.cs
src/Sextant.Tests/Navigation/ParameterViewStackServiceFixture.cs
src/Sextant.Tests/Navigation/ParameterViewStackServiceTests.cs
src/Sextant.Tests/Navigation/ViewStackServiceFixture.cs
src/Sextant.Tests/Navigation/ViewStackServiceTests.cs
src/Sextant.Tests/Sextant.Tests.csproj
src/Sextant.Tests/ViewModelFactoryTests.cs
src/Sextant.XamForms.Tests/API/ApiApprovalTests.cs
src/Sextant.XamForms.Tests/DependencyResolverMixinTests.cs
src/Sextant.XamForms.Tests/Sextant.XamForms.Tests.csproj
src/Sextant.XamForms.Tests/SextantExtensionTests.cs
src/Sextant/Abstractions/IViewModelFactory.cs
src/Sextant/DefaultViewModelFactory.cs
src/Sextant/DependencyResolverMixins.cs
src/Sextant/Navigation/ParameterViewStackService.cs
src/Sextant/Navigation/ViewStackService.cs
src/Sextant/Navigation/ViewStackServiceBase.cs
src/Sextant/Platforms/netstandard2.0/SextantExtensions.cs
src/Sextant/Platforms/uap/NavigationView.xaml.cs
src/Sextant/Sextant.cs
src/Sextant/System/Reactive/Linq/SubscribeSafeExtensions.cs
src/Sextant/ViewModelFactory.cs
src/Sextant/ViewModelFactoryNotFoundException.cs
src/xunit.runner.json

fixes issues with contracts not being passed through for ViewModel location.
Resolves #230 
ViewModel Contracts are now passed all the way through for resolution.
potentially consumers registering `ViewStackService` themselves as I changed the implementation to take a dependency on the `IViewModelFactory` for testability.

fix: ViewModelFactory not using passed contract

---

README.md

docs
a couple of the links currently point to master, so 404 following the rename to main
use main
the sextant logo comes from master in the styleguide, as and when that updates, this will probably break

docs: rename master to main in docs

---

src/Sextant.iOS.Runner/NavigationViewControllerTests.cs
src/Sextant.iOS.Runner/Sextant.iOS.Runner.csproj

We've converted most of the other projects over to using FluentAssertions, just converting the iOS tests to also use FluentAssertions.

housekeeping: Remove more shouldly references

---

src/Directory.build.props

Swap to using the new NetAnalyzers which replaces the FxCop ones.
Update to latest Stylecop Analyzers which support C# 9 syntax.

housekeeping: Update analyzers

---

src/Sextant.Tests/API/ApiApprovalTests.Sextant.net5.0.approved.txt
src/Sextant.Tests/API/ApiApprovalTests.Sextant.netcoreapp3.1.approved.txt
src/Sextant.Tests/Navigation/NavigationParameterTests.cs
src/Sextant/Abstractions/INavigationParameter.cs
src/Sextant/Navigation/NavigationParameter.cs

Adds genetic value methods for getting parameters.
You have to cast them yourself.
use a generic `Get` or `TryGet`
navigation parameters

feature: add GetValue methods to INavigationParameter

---

src/Sextant.Tests/API/ApiApprovalTests.Sextant.net5.0.approved.txt
src/Sextant.Tests/API/ApiApprovalTests.Sextant.netcoreapp3.1.approved.txt
src/Sextant.Tests/Navigation/ParameterViewStackServiceTests.cs
src/Sextant.Tests/Navigation/ViewStackServiceTests.cs
src/Sextant/Navigation/ParameterViewStackService.cs
src/Sextant/Navigation/ViewStackService.cs
src/Sextant/Navigation/ViewStackServiceBase.cs

fixes: #306 
The base implementation is passing null expecting the value to come from registration.
The constructor provides a new instance.

fix: ParameterViewStackService passing null on construction

---

src/Sextant.Mocks/NavigableViewModelMock.cs
src/Sextant.Tests/API/ApiApprovalTests.Sextant.net5.0.approved.txt
src/Sextant.Tests/API/ApiApprovalTests.Sextant.netcoreapp3.1.approved.txt
src/Sextant.Tests/DependencyResolverMixinTests.cs
src/Sextant.Tests/Navigation/NavigationParameterTests.cs
src/Sextant/DependencyResolverMixins.cs

feature: Added RegisterViewForNavigation method
